# permissions for end users to view livecontainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livecontainer-viewer-role
rules:
- apiGroups:
  - app.kubebuilder.io
  resources:
  - livecontainers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.kubebuilder.io
  resources:
  - livecontainers/status
  verbs:
  - get
