# permissions for end users to edit livecontainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: livecontainer-editor-role
rules:
- apiGroups:
  - app.kubebuilder.io
  resources:
  - livecontainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.kubebuilder.io
  resources:
  - livecontainers/status
  verbs:
  - get
