apiVersion: app.kubebuilder.io/v1
kind: LiveContainer
metadata:
  name: livecontainer-sample
  namespace: liuweibin
spec:
  # TODO(user): Add fields here
  schedulerName: volcano
  image: repository:tag
  imagePullPolicy: Always
  timeout: 60
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "50Gi"
      cpu: "20"
  ports:
  - containerPort: 22
    name: ssh-port
    hostPort: 1913
